
common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 
  password:

development:
  <<: *common
  database: stasheyboard_development

test: 
  <<: *common
  database: stasheyboard_test

production:
  <<: *common
  database: stasheyboard_production

